/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MedicalHistoryRequestDto } from '../../models/medical-history-request-dto';

export interface CompleteMedicalHistory$Params {
  appointmentId: number;
      body: MedicalHistoryRequestDto
}

export function completeMedicalHistory(http: HttpClient, rootUrl: string, params: CompleteMedicalHistory$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, completeMedicalHistory.PATH, 'post');
  if (params) {
    rb.path('appointmentId', params.appointmentId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

completeMedicalHistory.PATH = '/medical-history/appointment/{appointmentId}/complete';
