/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FeedbackResponse } from '../../models/feedback-response';

export interface GetFeedbackForDoctor$Params {
}

export function getFeedbackForDoctor(http: HttpClient, rootUrl: string, params?: GetFeedbackForDoctor$Params, context?: HttpContext): Observable<StrictHttpResponse<FeedbackResponse>> {
  const rb = new RequestBuilder(rootUrl, getFeedbackForDoctor.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<FeedbackResponse>;
    })
  );
}

getFeedbackForDoctor.PATH = '/feedback/doctor/feedback';
