/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FeedbackDto } from '../models/feedback-dto';
export interface AppointmentDto {
  dateAppointment?: string;
  doctorName?: string;
  feedback?: Array<FeedbackDto>;
  hospital?: string;
  id?: number;
  patientName?: string;
  reason?: string;
  specialization?: string;
  status?: string;
}
