/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Feedback } from '../models/feedback';
import { MedicalHistory } from '../models/medical-history';
import { User } from '../models/user';
export interface Appointment {
  appointmentDate?: string;
  doctor?: User;
  feedback?: Array<Feedback>;
  id?: number;
  medicalHistory?: MedicalHistory;
  patient?: User;
  reason?: string;
  status?: string;
}
