/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AppointmentRequest {
  dateAppointment?: string;
  doctorId?: number;
  reason?: string;
}
