/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DoctorDto {
  averageRating?: number;
  firstname?: string;
  hospital?: string;
  id?: number;
  lastname?: string;
  specialization?: string;
}
