/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FeedbackDto {
  comment?: string;
  createdDate?: string;
  patientName?: string;
  rating?: number;
}
