/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FeedbackDto } from '../models/feedback-dto';
export interface FeedbackResponse {
  averageRating?: number;
  doctorId?: number;
  feedbacks?: Array<FeedbackDto>;
}
