/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MedicalHistoryDto {
  additionalInfo?: string;
  appointmentDate?: string;
  diagnosis?: string;
  doctorName?: string;
  id?: number;
  patientName?: string;
  treatment?: string;
}
