/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Patient Data Transfer Object
 */
export interface PatientDto {

  /**
   * Patient's address
   */
  address?: string;

  /**
   * Patient's CNP
   */
  cnp?: string;

  /**
   * Patient's date of birth
   */
  dateOfBirth?: string;

  /**
   * Patient's first name
   */
  firstname?: string;

  /**
   * Patient's unique identifier
   */
  id?: number;

  /**
   * Patient's last name
   */
  lastname?: string;

  /**
   * Patient's phone number
   */
  phoneNumber?: string;
}
