/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateUserRequest {
  address?: string;
  dateOfBirth?: string;
  email?: string;
  firstname?: string;
  hospital?: string;
  lastname?: string;
  phoneNumber?: string;
  specialization?: string;
}
