/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DoctorDto } from '../../models/doctor-dto';

export interface GetDoctorsBySpecAndHospital$Params {
  specialization: string;
  hospital: string;
}

export function getDoctorsBySpecAndHospital(http: HttpClient, rootUrl: string, params: GetDoctorsBySpecAndHospital$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<DoctorDto>>> {
  const rb = new RequestBuilder(rootUrl, getDoctorsBySpecAndHospital.PATH, 'get');
  if (params) {
    rb.query('specialization', params.specialization, {});
    rb.query('hospital', params.hospital, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<DoctorDto>>;
    })
  );
}

getDoctorsBySpecAndHospital.PATH = '/appointments/doctors';
