/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { getAllDoctors } from '../fn/admin-controller/get-all-doctors';
import { GetAllDoctors$Params } from '../fn/admin-controller/get-all-doctors';
import { getAllPatients } from '../fn/admin-controller/get-all-patients';
import { GetAllPatients$Params } from '../fn/admin-controller/get-all-patients';
import { updateUser } from '../fn/admin-controller/update-user';
import { UpdateUser$Params } from '../fn/admin-controller/update-user';
import { User } from '../models/user';

@Injectable({ providedIn: 'root' })
export class AdminControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `updateUser()` */
  static readonly UpdateUserPath = '/admin/{userId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateUser()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateUser$Response(params: UpdateUser$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return updateUser(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateUser$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateUser(params: UpdateUser$Params, context?: HttpContext): Observable<string> {
    return this.updateUser$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

  /** Path part for operation `getAllPatients()` */
  static readonly GetAllPatientsPath = '/admin/get-admin-patients';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllPatients()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllPatients$Response(params?: GetAllPatients$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<User>>> {
    return getAllPatients(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllPatients$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllPatients(params?: GetAllPatients$Params, context?: HttpContext): Observable<Array<User>> {
    return this.getAllPatients$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<User>>): Array<User> => r.body)
    );
  }

  /** Path part for operation `getAllDoctors()` */
  static readonly GetAllDoctorsPath = '/admin/get-admin-doctors';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllDoctors()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllDoctors$Response(params?: GetAllDoctors$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<User>>> {
    return getAllDoctors(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllDoctors$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllDoctors(params?: GetAllDoctors$Params, context?: HttpContext): Observable<Array<User>> {
    return this.getAllDoctors$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<User>>): Array<User> => r.body)
    );
  }

}
