/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { AdminUserRequest } from './models/admin-user-request';
export { Appointment } from './models/appointment';
export { AppointmentDto } from './models/appointment-dto';
export { AppointmentRequest } from './models/appointment-request';
export { AuthenticationRequest } from './models/authentication-request';
export { AuthenticationResponse } from './models/authentication-response';
export { DoctorDto } from './models/doctor-dto';
export { DoctorRegistrationRequest } from './models/doctor-registration-request';
export { Feedback } from './models/feedback';
export { FeedbackDto } from './models/feedback-dto';
export { FeedbackRequest } from './models/feedback-request';
export { FeedbackResponse } from './models/feedback-response';
export { GrantedAuthority } from './models/granted-authority';
export { MedicalHistory } from './models/medical-history';
export { MedicalHistoryDto } from './models/medical-history-dto';
export { MedicalHistoryRequestDto } from './models/medical-history-request-dto';
export { PatientDto } from './models/patient-dto';
export { PatientRegistrationRequest } from './models/patient-registration-request';
export { Role } from './models/role';
export { UpdateUserRequest } from './models/update-user-request';
export { User } from './models/user';
