/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { UserControllerService } from './services/user-controller.service';
export { AdminControllerService } from './services/admin-controller.service';
export { MedicalHistoryService } from './services/medical-history.service';
export { FeedbackService } from './services/feedback.service';
export { AuthenticationService } from './services/authentication.service';
export { AppointmentService } from './services/appointment.service';
